[package]
name = "ai-digest"
version = "0.1.0"
authors = ["Aditya <adityabhatperdoor@gmail.com>"]
edition = "2021"

[dependencies]
clap = "4.5.23"
walkdir = "2.5.0"
rayon = "1.10.0"

[dev-dependencies]
tempfile = "3.14.0"

